export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://agendaclinica.space";

export const SEO_METADATA = {
  title: "Agenda Clínica Online | Reservas de pacientes, fichas clínicas y odontogramas",
  description: "AgendaClinica es un software de agenda online para clínicas y profesionales de salud: reservas de pacientes, fichas clínicas digitales, odontogramas, recordatorios por WhatsApp y correo, pagos y gestión clínica.",
  keywords: [
    "agenda online",
    "agenda online pacientes",
    "agenda online para clinicas",
    "agenda online para clínicas",
    "agenda clinica",
    "agenda clínica",
    "agenda clinica online",
    "agenda clínica online",
    "reserva de pacientes",
    "reservas de pacientes",
    "sistema de reservas para pacientes",
    "fichas clinicas",
    "fichas clínicas",
    "fichas clinicas digitales",
    "fichas clínicas digitales",
    "ficha clinica digital",
    "ficha clínica digital",
    "historial clinico pacientes",
    "historial clínico pacientes",
    "odontograma",
    "odontogramas",
    "software odontologico",
    "software odontológico",
    "agenda odontologica",
    "agenda odontológica",
    "recordatorios automáticos",
    "recordatorios whatsapp pacientes",
    "recordatorios por whatsapp",
    "agenda medica",
    "agenda médica",
    "software para clinicas",
    "software para clínicas",
    "gestion de pacientes",
    "gestión de pacientes",
    "agenda para odontologos",
    "agenda para odontólogos",
    "agenda para psicologos",
    "agenda para psicólogos",
    "agenda para kinesiologos",
    "agenda para kinesiólogos",
    "sistema de agendamiento medico",
    "sistema de agendamiento médico",
    "software medico chile",
    "software médico Chile",
    "software clinico chile",
    "software clínico Chile",
  ],
  authors: [{ name: "NativeCode SpA" }],
  creator: "NativeCode SpA",
  publisher: "NativeCode SpA",
};
